### ISSUE TITLE
Panel UI/UX Review 

### ISSUE THREAD

**Issue by TheHadiAhmadi** [fluentcms/FluentCMS#968]
# TODOS

## SetupPage

- [x] #1057
- [x] #1059
- [x] #1055
- [x] #1085
- [x] #1066
- [x] #1094
- [ ] ~Redirect to /setup page if application is not initialized~ (infrastructure) (need teeam review)
- [ ] UX Writing #1039

## Sidebar

- [x] Highlight active Sidebar item (primary & secondary sidebars) #1067
- [x] Remove unused spacing from sidebar items (top of ContentManager) #1067
- [x] #1072
- [x] Fix typography and alignment of Secondary sidebar's title #1067
- [x] (component) Show overlay for sidebar in mobile mode #1067
- [x] #1135
- [x] #1136
- [x] #1115

## Homepage

- [x] #1117
- [x] #1073
- [x] (home) Home page needs content (**hero section**)
- [x] #1141

## Panel

- [x] #1080
- [x] #1061
- [x] (panel) Add `(Draft)` next to title of pages that are not fully working.
- [x] #1143
- [x] (panel, mobile view) Safe-environemnt padding in bottom of pages. env(safe-area-inset-bottom). (#898)
- [ ] ~(panel) Add constant routes exmaple /auth/login~ (infrastructure)

## New Components

- [x] #1090
- [x] #1105
- [x] #1109
- [x] #1110
- [x] #1113

## Form 
- [x] #1163
- [ ] #1164
- [ ] (form) Autofucus is not working sometimes
- [ ] ~(form) Email Validation is not working~ (infrastructure)
- [ ] (form) Errors should be human friendly (not texts like `ContentType.DuplicateSlug` ...)
- [ ] (form) Some checkboxes are not accessible. when clicked on label it doesn't toggle.
- [ ] (form) Localization

## ContentType

- [x] #1075
- [ ] (contentType) Title of field modal should be equal to name of current content type (not `Article`)
- [ ] (contentType) move tabs to right, move `Add Field` title to left of tabs and add name of ContentType in modal Header. (similar to strapi) **Important**
- [ ] (contentType) After creating content type, should open modal of `+ Add field` automatically
- [ ] (contentType, form) Move all cancel buttons to left side. 

## Content

- [x] #1096
- [x] #1094
- [x] #1096
- [ ] (content) design Content preview page.

# Misc 

- [x] #1101
- [x] (table) Remove Table header from empty states.
- [x] #1063
- [x] #1099
- [x] #1077
- [x] (settings) Title of /admin/users should be `Users`
- [x] (settings) Title of /admin/roles should be `Roles`

# Code review
- [ ] #1165
- [x] #1148
- [x] #1150
- [ ] Clean experimental codes footprints
- [ ] Code quality
- [ ] Move app component to app project
- [ ] Component Naming Guide Line
- [ ] make base components project ready to use in other projects
- [ ] Review tailwindcss class order when using with @apply
- [ ] check Default values of components (Gutter=medium.., hasBack=true)

# Enhancment
- [ ] Prettier
- [ ] Code long scroll problem
- [ ] (contentType) add `+ Add another field` button in field modal.
- [ ] * (panel) Header should be sticky and cancel & submit button should be inside header.
- [ ] (contentType) show count of contents of current contentType in table (**not important**)
- [ ] Improve import js files
- [ ] (component) Add Expansion panel component **Not for MVP**
