### ISSUE TITLE
The MVP Roadmap

### ISSUE THREAD

**Issue by abdolian** [fluentcms/FluentCMS#969]
- [x] Drop app feature
- [x] Fix flicker on dark mode
- [ ] FluentCMS landing page
- [ ] Branding
- [x] Add authentication 
- [ ] Add validation on DTOs
- [ ] Add global settings
- [ ] Add email provider
- [ ] Support basic content types (Boolean, Date, Email, Enumeration, Markdown, Number, Password, Text, Media)
- [ ] Add file management system
- [x] Add change password
- [ ] Add forgot/reset password
- [ ] Support LiteDB
